### ISSUE TITLE
大佬，您能导入窗口为16的预训练权重吗

### ISSUE THREAD

**Issue by LUO77123** [ChristophReich1996/Swin-Transformer-V2#10]
源码改建
（当我导入swinv2_tiny_patch4_window8_256.pth，使用窗口为8时候，可以正常跑代码；但是当我导入swinv2_tiny_patch4_window16_256.pth，使用窗口为16时候，导入权重出现不匹配情况；不知道如何处理，请大佬解答一下。
问题如下：）
RuntimeError: Error(s) in loading state_dict for Model:
size mismatch for model.7.blocks.0.attn.relative_coords_table: copying a param with shape torch.Size([1, 15, 15, 2]) from checkpoint, the shape in current model is torch.Size([1, 31, 31, 2]).
size mismatch for model.7.blocks.0.attn.relative_position_index: copying a param with shape torch.Size([64, 64]) from checkpoint, the shape in current model is torch.Size([256, 256]).
size mismatch for model.7.blocks.1.attn.relative_coords_table: copying a param with shape torch.Size([1, 15, 15, 2]) from checkpoint, the shape in current model is torch.Size([1, 31, 31, 2]).
size mismatch for model.7.blocks.1.attn.relative_position_index: copying a param with shape torch.Size([64, 64]) from checkpoint, the shape in current model is torch.Size([256, 256]).

**Comment by ChristophReich1996** [comment]
Hi @LUO77123, 

Sorry for my late reponse. You need to initialize the model with the same parameters as used for generating the checkpoints. After loading you can change the resolution, window size, and other settings. Please refer to [this answer](https://github.com/ChristophReich1996/Swin-Transformer-V2/issues/9#issuecomment-1098162968).

Cheers,
Christoph
