### ISSUE TITLE
How to use for SSL or classifier?

### ISSUE THREAD

**Issue by sarmientoj24** [ChristophReich1996/Swin-Transformer-V2#12]
Since it produces feature maps, how do I "flatten" the feature maps for the classifier?

**Comment by ChristophReich1996** [comment]
Hi @sarmientoj24, Sorry for my late response. Have a look at the image classification code [here](https://github.com/ChristophReich1996/Swin-Transformer-V2/blob/7b74308bd560a5efabc0f9610d038dcf8e61226e/image_classification/utils.py#L97). This class just wraps the model for classification.
