### ISSUE TITLE
3D segmentation

### ISSUE THREAD

**Issue by RRouhi** [ChristophReich1996/Swin-Transformer-V2#14]
Thank you for your interesting work.
Is there a 3D implementation for medical image segmentation like .nifti images?

Thanks!

**Comment by ChristophReich1996** [comment]
Hi @RRouhi, this implementation only includes a 2D Swin implementation. I would recommend checking out [this paper](https://arxiv.org/pdf/2204.00631.pdf) and [this repo](https://github.com/Project-MONAI/research-contributions/tree/main). I hope this helps!

**Comment by RRouhi** [comment]
Thank you!
I cannot see the code at the link provided :
https://github.com/Project-MONAI/research-contributions
