### ISSUE TITLE
Training and inference implementation of Swin v.2 for oject detection task 

### ISSUE THREAD

**Issue by queman** [ChristophReich1996/Swin-Transformer-V2#6]
Hi,
I've worked on Swin Transformer v.1 earlier for object detection training and inference. Now I want to improve the result with Swin Transformer v.2. Is it available and is there any way to do that?
Many thanks.

**Comment by larsoncs** [comment]
I look forwarding for it.

**Comment by ChristophReich1996** [comment]
Hi @queman and @larsoncs, thanks for the interest! I don't plan to offer an object detection training example, however, it should be able to swap the Swin V1 with the Swin V2 implementation without too much effort, since in the end, you are only changing the backbone of your object detection model.
